# Generic postprocessing of the panel properties generated by a near-field
# force model. These utilities are intentionally separate from the retained
# legacy Imperial segment-force implementation.

"""
    body_forces(system; frame=Body())

Return the total force and moment coefficients after a near-field analysis.
"""
function body_forces(system::System; frame = Body())
    @assert system.near_field_analysis[] "Near field analysis required"
    return body_forces(
        system.surfaces,
        system.properties,
        system.reference[],
        system.freestream[],
        system.symmetric,
        frame,
    )
end

"""
    body_forces(surfaces, properties, reference, freestream, symmetric, frame)

Reduce normalized panel forces to total force and moment coefficients.
"""
function body_forces(surfaces, properties, reference, freestream, symmetric, frame)
    scalar_type = eltype(eltype(eltype(properties)))
    total_force = zero(SVector{3, scalar_type})
    total_moment = zero(SVector{3, scalar_type})

    for surface_index in eachindex(surfaces)
        surface_force = zero(total_force)
        surface_moment = zero(total_moment)

        for panel_index in eachindex(surfaces[surface_index])
            panel = surfaces[surface_index][panel_index]
            panel_properties = properties[surface_index][panel_index]

            for (location, force) in (
                (top_center(panel), panel_properties.cfb),
                (left_center(panel), panel_properties.cfl),
                (right_center(panel), panel_properties.cfr),
            )
                surface_force += force
                surface_moment += cross(location - reference.r, force)
            end
        end

        if symmetric[surface_index]
            surface_force = SVector(
                2 * surface_force[1],
                zero(scalar_type),
                2 * surface_force[3],
            )
            surface_moment = SVector(
                zero(scalar_type),
                2 * surface_moment[2],
                zero(scalar_type),
            )
        end

        total_force += surface_force
        total_moment += surface_moment
    end

    reference_length = SVector(reference.b, reference.c, reference.b)
    total_moment = total_moment ./ reference_length
    total_moment = total_moment .* SVector(-1, 1, -1)
    return body_to_frame(total_force, total_moment, reference, freestream, frame)
end

"""
    body_forces_derivatives(system)

Return body-frame force and moment coefficients and their stored derivatives.
"""
function body_forces_derivatives(system::System)
    @assert system.near_field_analysis[] "Near field analysis required"
    @assert system.derivatives[] "Derivative computations required"

    reference = system.reference[]
    freestream = system.freestream[]
    arguments = (system.surfaces, reference, freestream, system.symmetric, Body())
    force, moment = body_forces(system.surfaces, system.properties,
        reference, freestream, system.symmetric, Body())
    # Preserve the historical derivative API: its base moment precedes the
    # roll/yaw convention change applied by `body_forces`, while each stored
    # moment derivative includes that convention change.
    moment = moment .* SVector(-1, 1, -1)

    derivative_results = map(system.dproperties) do derivative_properties
        body_forces(system.surfaces, derivative_properties, arguments[2:end]...)
    end
    force_derivatives = Tuple(first(result) for result in derivative_results)
    moment_derivatives = Tuple(last(result) for result in derivative_results)
    return force, moment, force_derivatives, moment_derivatives
end

"""
    body_forces_history(system, surface_history, property_history; frame=Body())

Return total force and moment coefficient histories.
"""
function body_forces_history(
    system,
    surface_history::AbstractVector{<:AbstractVector{<:AbstractMatrix}},
    property_history;
    frame = Body(),
)
    number_of_steps = length(property_history)
    freestream_history = system.freestream[] isa Freestream ?
        fill(system.freestream[], number_of_steps) : system.freestream[]
    scalar_type = eltype(system)
    force_history = Vector{SVector{3, scalar_type}}(undef, number_of_steps)
    moment_history = similar(force_history)

    for step in eachindex(property_history)
        force_history[step], moment_history[step] = body_forces(
            surface_history[step],
            property_history[step],
            system.reference[],
            freestream_history[step],
            system.symmetric,
            frame,
        )
    end
    return force_history, moment_history
end

"""
    lifting_line_coefficients(system, positions, chords; frame=Body())

Return force and moment coefficients per unit span for each lifting line.
"""
function lifting_line_coefficients(system, positions, chords; frame = Body())
    scalar_type = promote_type(
        eltype(system),
        eltype(eltype(positions)),
        eltype(eltype(chords)),
    )
    number_of_surfaces = length(system.surfaces)
    force_coefficients = Vector{Matrix{scalar_type}}(undef, number_of_surfaces)
    moment_coefficients = similar(force_coefficients)

    for surface_index in eachindex(system.surfaces)
        number_spanwise = size(system.surfaces[surface_index], 2)
        force_coefficients[surface_index] =
            Matrix{scalar_type}(undef, 3, number_spanwise)
        moment_coefficients[surface_index] =
            Matrix{scalar_type}(undef, 3, number_spanwise)
    end
    return lifting_line_coefficients!(
        force_coefficients,
        moment_coefficients,
        system,
        positions,
        chords;
        frame,
    )
end

function lifting_line_coefficients(system; frame = Body(), xc = 0.25)
    positions, chords = lifting_line_geometry(system.grids, xc)
    return lifting_line_coefficients(system, positions, chords; frame)
end

"""
    lifting_line_coefficients!(force_coefficients, moment_coefficients,
        system, positions, chords; frame=Body())

In-place version of [`lifting_line_coefficients`](@ref).
"""
function lifting_line_coefficients!(
    force_coefficients,
    moment_coefficients,
    system,
    positions,
    chords;
    frame = Body(),
)
    @assert system.near_field_analysis[] "Near field analysis required"
    reference = system.reference[]
    freestream = system.freestream[]

    for surface_index in eachindex(system.surfaces)
        panels = system.surfaces[surface_index]
        properties = system.properties[surface_index]
        number_chordwise, number_spanwise = size(panels)

        for spanwise_index in 1:number_spanwise
            left_position = SVector(
                positions[surface_index][1, spanwise_index],
                positions[surface_index][2, spanwise_index],
                positions[surface_index][3, spanwise_index],
            )
            right_position = SVector(
                positions[surface_index][1, spanwise_index + 1],
                positions[surface_index][2, spanwise_index + 1],
                positions[surface_index][3, spanwise_index + 1],
            )
            segment_length = norm(right_position - left_position)
            reference_position = (left_position + right_position) / 2
            reference_chord = (
                chords[surface_index][spanwise_index] +
                chords[surface_index][spanwise_index + 1]
            ) / 2
            section_force = zero(SVector{3, eltype(force_coefficients[surface_index])})
            section_moment = zero(section_force)

            for chordwise_index in 1:number_chordwise
                panel = panels[chordwise_index, spanwise_index]
                panel_properties = properties[chordwise_index, spanwise_index]
                for (location, force) in (
                    (top_center(panel), panel_properties.cfb),
                    (left_center(panel), panel_properties.cfl),
                    (right_center(panel), panel_properties.cfr),
                )
                    section_force += force
                    section_moment += cross(location - reference_position, force)
                end
            end

            section_force *= reference.S / (segment_length * reference_chord)
            section_moment *= reference.S /
                (segment_length * reference_chord^2)
            section_force, section_moment = body_to_frame(
                section_force,
                section_moment,
                reference,
                freestream,
                frame,
            )
            force_coefficients[surface_index][:, spanwise_index] = section_force
            moment_coefficients[surface_index][:, spanwise_index] = section_moment
        end
    end
    return force_coefficients, moment_coefficients
end

body_to_frame(force, moment, reference, freestream, ::Body) = force, moment

function body_to_frame(force, moment, reference, freestream, ::Stability)
    rotation = body_to_stability(freestream)
    return rotation * force, rotation * moment
end

function body_to_frame(force, moment, reference, freestream, ::Wind)
    reference_length = SVector(reference.b, reference.c, reference.b)
    rotation = body_to_wind(freestream)
    transformed_force = rotation * force
    transformed_moment = rotation * (moment .* reference_length)
    return transformed_force, transformed_moment ./ reference_length
end
